openapi: 3.0.3
info:
  title: ATLAS feeding_data
  description: Send planned rations and get actual feeding reports into the system.
  version: '0.0.2'
servers:
  - url: http://localhost:8080
    description: Inferred Url
security: 
  - "bearerAuth": []
paths:
  /feedingreport:
    get:
      summary: Retrieve feeding report
      parameters:
        - name: start_date
          in: query
          description: Start date from when to fetch data, ISO8601 date
          required: true
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: End date from when to fetch data, ISO8601 date
          required: true
          schema:
            type: string
            format: date
        - name: ration_ref
          in: query
          description: ration_ref is an optional identifier to connect rations between different systems
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeDailyReport'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /ration:
    post:
      summary: importRation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RationRequest'
      responses:
        '204':
          description: Successful import
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    URN:
        type: "string"
        pattern: "^urn:[a-z][a-z0-9_.\\-]*:[\\w-.]+"
        description: "Uniform resource name of a pen with the syntax `urn:<service_id>:<internal_id>`. <service_id> must be the id of a valid and active ATLAS service"
        example: 'urn:de.fodjan.animal_data:69d4a4ec-e8a4-4768-a299-14a7a9acd1b1'
    RationFeedstuffRequest:
      title: RationFeedstuffRequest
      type: object
      properties:
        amount_freshmatter:
          type: number
          description: Fresh matter amount of feedstuff in ration (kg)
          format: double
        cost_kg_freshmatter:
          type: number
          description: Fresh matter cost per kg of ration feedstuff (USD)
          format: double
          example: 0.4125
        drymatter_percentage:
          type: number
          description: DM percentage of ration feedstuff
          format: double
          example: 0.55
        feedstuff_id:
          type: string
          description: feedstuff_id represent identification number of ration feedstuff between systems
          example: 49c78036-acfb-11ed-afa1-0242ac120002
        name:
          type: string
          description: Name of ration feedstuff
          example: Sojabohnen (gesch., Bioprofin)
        type:
          type: string
          description: Feed type of feedstuff in ration, todo check completeness
          enum: 
            - dry_forage
            - corn_silage
            - alfa_silage
            - grass_silage
            - other_wet_forage
            - by_product
            - grain
            - fatty_acid_source
            - triglycerides
            - cp_source
            - rup_source
            - mineral
            - miscellaneous
            - vitamin
            - premix
            - forage
            - concentrate
            - commercial
            - water
          example: dry_forage
      required:
        - amount_drymatter
        - drymatter_percentage
        - feedstuff_id
        - name
        - type
    RationRequest:
      title: RationRequest
      type: object
      properties:
        ration_ref:
          type: string
          description: client-supplied reference for that ration. If ration_ref is not provided, new ration will be created. If ration_ref is already known, existing ration will be updated.
          example: 62559890-acfb-11ed-afa1-0242ac120002
        feedstuffs:
          type: array
          description: Order of feedstuff in this array will be used as order of feedstuff in mixer wagon
          items:
            $ref: '#/components/schemas/RationFeedstuffRequest'
        pen_allocations:
          type: array
          items:
            $ref: '#/components/schemas/PenAllocation'
        name:
          type: string
          description: Ration name
          example: Ration Test 1
        start_date: 
          type: string
          format: date
          description: Start date of ration, as ISO8601 date
      required:
        - feedstuffs
        - pens
        - name
    PenAllocation:
      title: Pen
      type: object
      description: Describes which pen get how much freshmass per animal. Use the number of animals from the animal_data GET /pens interface
      properties:
        feed_intake_per_animal:
          type: number
          description: Feed intake per animal in freshmass kg per day
          format: double
          example: 31.5
        urn:
          $ref: "#/components/schemas/URN"
    RecipeDailyReport:
      title: RecipeDailyReport
      type: object
      properties:
        loadings:
          type: array
          description: List of all loadings per day
          items:
            $ref: '#/components/schemas/Loading'
        ration_ref:
          type: string
          description: ration_ref is an optional identifier to connect rations between different systems
          example: 40ac1b42-acfb-11ed-afa1-0242ac120002
    Unloading:
      title: Unloading
      type: object
      properties:
        start_date:
          type: string
          description: Unloading start date and time (UTC time)
          example: '2020-11-06T08:35:53Z'
          format: date-time
        end_date:
          type: string
          description: Unloading finish date and time (UTC time)
          example: '2020-11-06T09:35:53Z'
          format: date-time
        pen_urn:
          $ref: "#/components/schemas/URN"
        corrected_number_of_animals:
          type: integer
          description: Number of animals in the pen. Can be corrected by the user for that single feeding
          format: int64
          example: 62
        unloaded_amount_kg:
          type: number
          description: Unloaded amount in this pen from feeding load in kg freshmass for this unloading
          format: double
          example: 900
    Loading:
      title: Loading
      type: object
      properties: 
        start_date:
          type: string
          description: Loading start date and time (UTC time)
          example: '2020-11-06T08:35:53Z'
          format: date-time
        end_date:
          type: string
          description: Loading finish date and time (UTC time)
          example: '2020-11-06T09:35:53Z'
          format: date-time
        feedstuffs:
          type: array
          description: List of feedstuffs loaded into feedwagon
          items:
            $ref: '#/components/schemas/FeedstuffsLoading'
        unloadings:
          type: array
          description: List of unloadings per day
          items:
            $ref: '#/components/schemas/Unloading'
    FeedstuffsLoading:
      title: Ingredients
      type: object
      properties:
        calculated_amount_kg:
          type: number
          description: Calculated amount of feed in feeding load in kg freshmass
          format: double
          example: 780
        feedstuff_id:
          type: string
          description: feedstuff id, same as in ration feedstuffs
          example: f627dfc6-ad03-11ed-afa1-0242ac120002
        loaded_amount_kg:
          type: number
          description: Actual amount of feedstuff in feeding load in kg freshmass
          format: double
          example: 750
  securitySchemes:
    bearerAuth: 
      type: "http"
      scheme: "bearer"
      
